package com.github.nalukit.nalu.simple.app.client;

import com.github.nalukit.nalu.plugin.elemental2.client.NaluPluginElemental2;
import com.google.gwt.core.client.EntryPoint;
import com.google.gwt.core.client.GWT;
import elemental2.dom.DomGlobal;
import elemental2.dom.Element;
import org.dominokit.domino.ui.forms.FieldStyle;
import org.dominokit.domino.ui.utils.DominoUIConfig;
import org.dominokit.rest.DominoRestConfig;

/**
 * Copyright (C) 2018 - 2021 Frank Hossfeld <frank.hossfeld@googlemail.com>
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
public class App
    implements EntryPoint {

  public void onModuleLoad() {
    GWT.setUncaughtExceptionHandler(e -> GWT.log("PANIC! -> UncaughtException Handler called"));
    // initialize domino rest
    DominoRestConfig.initDefaults();
    DominoRestConfig.getInstance()
                    .setDefaultFailHandler(failedResponse -> {
                      DomGlobal.window.alert("PANIC!!!!!");
                    });
    // remove default buttom margin from fields
    DominoUIConfig.INSTANCE.setDefaultFieldsStyle(FieldStyle.ROUNDED)
                           .setCondensed(true);
    // Create the application.
    // The ApplicationImpl-class
    // will be generated by the framework.
    AppApplication application = new AppApplicationImpl();
    // start the application by calling the run()-method.
    application.run(new NaluPluginElemental2());
    // remove the loaing spinner ...
    Element ele = DomGlobal.document.getElementById("LoadingSpinner");
    if (ele != null) {
      ele.remove();
    }
  }

}
